<a href="https://colab.research.google.com/github/ednavivianasegura/Curso_ML_Python/blob/main/Plan_de_Formacion_PDI_PAS_2026/02_pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:30%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
</style>

<div class="nb-cell" style="padding:1.5rem 0 2rem;">
  <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:1.5rem;padding-bottom:1.25rem;border-bottom:2px solid #1E3A8A;">
    <div style="flex:1;">
      <span style="display:inline-block;font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#0F766E;background:#CCFBF1;border:1px solid #5EEAD4;padding:3px 10px;border-radius:20px;margin-bottom:8px;">Plan de Formación PDI/PAS 2026</span>
      <div style="font-size:11px;color:#475569;letter-spacing:.6px;text-transform:uppercase;margin-bottom:6px;">Formación para la investigación</div>
      <div style="font-size:11px;font-style:italic;color:#475569;margin-bottom:4px;">Módulo 2 — Pandas 2</div>
      <h1 style="font-size:24px;font-weight:700;color:#1E3A8A;line-height:1.2;margin:0;">Python: Programación de IA</h1>
    </div>
    <div style="display:flex;flex-direction:column;align-items:center;gap:6px;flex-shrink:0;">
      <img src="https://github.com/ednavivianasegura/AccesoImages/blob/main/logoUR.png?raw=true" alt="Logo UR" style="width:72px;height:auto;">
      <div style="font-size:9px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;text-align:center;line-height:1.4;">Universidad<br>de La Rioja</div>
    </div>
  </div>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px;">
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);"><i class="ti ti-list-check" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Contenidos</div>
      <div style="display:flex;flex-direction:column;gap:5px;">
        <div style="font-size:12.5px;color:#1e293b;display:flex;align-items:center;gap:8px;"><span style="display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#EFF6FF;border:1px solid #BFDBFE;color:#1E3A8A;font-size:10px;font-weight:600;flex-shrink:0;">1</span>map(), applymap() y apply()</div>
        <div style="font-size:12.5px;color:#1e293b;display:flex;align-items:center;gap:8px;"><span style="display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#EFF6FF;border:1px solid #BFDBFE;color:#1E3A8A;font-size:10px;font-weight:600;flex-shrink:0;">2</span>Valores nulos — NaN</div>
        <div style="font-size:12.5px;color:#1e293b;display:flex;align-items:center;gap:8px;"><span style="display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#EFF6FF;border:1px solid #BFDBFE;color:#1E3A8A;font-size:10px;font-weight:600;flex-shrink:0;">3</span>groupby() y funciones agregadas</div>
      </div>
    </div>
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);"><i class="ti ti-target" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Objetivo</div>
      <div style="font-size:12.5px;color:#1e293b;line-height:1.6;">Aplicar transformaciones avanzadas sobre Series y DataFrames, gestionar valores nulos y agrupar datos para obtener estadísticas resumidas.</div>
    </div>
  </div>
  <div style="display:flex;align-items:center;justify-content:space-between;padding:9px 14px;background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;font-size:11px;color:#94A3B8;">
    <span><i class="ti ti-school" style="font-size:12px;color:#1E3A8A;"></i> Universidad de La Rioja — Logroño, La Rioja</span>
    <span><i class="ti ti-calendar" style="font-size:12px;color:#1E3A8A;"></i> Plan de Formación PDI/PAS 2026</span>
  </div>
</div>

In [2]:
import numpy as np
import pandas as pd

In [3]:
!git clone https://github.com/ednavivianasegura/Curso_ML_Python.git

Cloning into 'Curso_ML_Python'...
remote: Enumerating objects: 1262, done.
remote: Counting objects: 100% (348/348), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 1262 (delta 327), reused 209 (delta 209), pack-reused 914 (from 1)
Receiving objects: 100% (1262/1262), 70.13 MiB | 27.89 MiB/s, done.
Resolving deltas: 100% (732/732), done.

In [7]:
import os
os.chdir("/content/Curso_ML_Python/Modulo1_b")

In [8]:
df = pd.read_csv("Data/titanic_1.csv")
df.head()

,PassengerId,Name,Sex,Age
0,1,"Braund, Mr. Owen Harris",male,22.0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,"Heikkinen, Miss. Laina",female,26.0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,5,"Allen, Mr. William Henry",male,35.0

In [10]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:30%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Series.map()</h3>
  <hr class="nb-divider">
 <div class="nb-body-box">
    <code class="ic">.map()</code> aplica una función a <strong>cada elemento</strong> de una
    Serie o DataFrame. Acepta una <strong>función lambda</strong>, una <strong>función normal</strong>
    o un <strong>diccionario</strong> como parámetro, y <strong>no es in-place</strong> —
    devuelve un nuevo objeto. El parámetro opcional <code class="ic">na_action='ignore'</code>
    permite omitir los <code class="ic">NaN</code> durante la transformación.
    </div>
  <div class="table-wrap">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Uso</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Descripción</th>
      </tr></thead>
      <tbody>
        <tr>
          <td><span class="tip"><code class="ic">.map(lambda x: f(x))</code><span class="tt">La función recibe cada elemento de la Serie como argumento x y devuelve el valor transformado.</span></span></td>
          <td class="desc">Aplica una <strong>función lambda</strong> elemento a elemento</td>
        </tr>
        <tr>
          <td><span class="tip"><code class="ic">.map(&#123;&quot;a&quot;: 1, &quot;b&quot;: 2&#125;)</code><span class="tt">Equivalente a .replace() con diccionario. Los valores que no están en el diccionario se convierten en NaN.</span></span></td>
          <td class="desc">Mapea valores usando un <strong>diccionario</strong></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="nb-note" style="margin-top:.8rem;">
    <i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="nb-note-text">Cuando se usa con diccionario, los valores que <strong>no aparecen como clave</strong> en el diccionario se convierten en <code class="ic">NaN</code>. Si se quiere conservarlos, es preferible usar <code class="ic">.replace()</code>.</span>
  </div>
</div>

In [11]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [12]:
# Raíz cuadrada de la edad
df["Age"].map(lambda x: np.sqrt(x))

0      4.690416
1      6.164414
2      5.099020
3      5.916080
4      5.916080
         ...
886    5.196152
887    4.358899
888         NaN
889    5.099020
890    5.656854
Name: Age, Length: 891, dtype: float64

In [13]:
# Multiplicar por 2
df["Age"].map(lambda x: x * 2)

0      44.0
1      76.0
2      52.0
3      70.0
4      70.0
       ...
886    54.0
887    38.0
888     NaN
889    52.0
890    64.0
Name: Age, Length: 891, dtype: float64

In [14]:
# Guardar en nueva columna
df["AgeSQRT"] = df["Age"].map(lambda x: np.sqrt(x))
df.head()

,PassengerId,Name,Sex,Age,AgeSQRT
0,1,"Braund, Mr. Owen Harris",male,22.0,4.690416
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,6.164414
2,3,"Heikkinen, Miss. Laina",female,26.0,5.099020
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,5.916080
4,5,"Allen, Mr. William Henry",male,35.0,5.916080

In [15]:
# La función lambda nos deja aplicar muchas funciones sin tener que definir una
# Extraer apellido
df["Surname"] = df["Name"].map(lambda x: x.split(",")[0])
df.head()

,PassengerId,Name,Sex,Age,AgeSQRT,Surname
0,1,"Braund, Mr. Owen Harris",male,22.0,4.690416,Braund
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,6.164414,Cumings
2,3,"Heikkinen, Miss. Laina",female,26.0,5.099020,Heikkinen
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,5.916080,Futrelle
4,5,"Allen, Mr. William Henry",male,35.0,5.916080,Allen

In [16]:
# Condicional en lambda
df["AgeSQRT"].map(lambda x: "mayor" if x > 5 else "menor")

0      menor
1      mayor
2      mayor
3      mayor
4      mayor
       ...
886    mayor
887    menor
888    menor
889    mayor
890    mayor
Name: AgeSQRT, Length: 891, dtype: object

In [17]:
# Con diccionario
df["Sex"].map({"male": "H", "female": "M"})

0      H
1      M
2      M
3      M
4      H
      ..
886    H
887    M
888    M
889    H
890    H
Name: Sex, Length: 891, dtype: object

In [18]:
# Equivalente con .replace()
df["Sex"].replace({"male": "H", "female": "M"})

0      H
1      M
2      M
3      M
4      H
      ..
886    H
887    M
888    M
889    H
890    H
Name: Sex, Length: 891, dtype: object

In [20]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.fn{color:#c4b5fd;}.st{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:30%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:6px;}
  .rb-green{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">map() y apply()</h3>
  <hr class="nb-divider">

  <div class="grid2">
    <div class="card">
      <div class="card-title"><i class="ti ti-vector" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Series/DataFrame.map()</div>
      <div class="card-body">Desde pandas 2.1, <code class="ic">.map()</code> funciona tanto sobre <strong>Series</strong> como sobre <strong>DataFrames</strong>. Aplica una función lambda o un diccionario a cada elemento individual.</div>
    </div>
    <div class="card">
      <div class="card-title"><i class="ti ti-adjustments" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Series/DataFrame.apply()</div>
      <div class="card-body">Más versátil — aplica la función a cada elemento (Series) o a cada columna o fila entera (DataFrame). Permite funciones más complejas que un lambda.</div>
    </div>
  </div>

  <div class="table-wrap">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Método</th>
        <th>Serie</th>
        <th>DataFrame</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Acepta</th>
        <th>Estado</th>
      </tr></thead>
      <tbody>
        <tr>
          <td><code class="ic">.map()</code></td>
          <td style="text-align:center;color:#0F766E;">✓</td>
          <td style="text-align:center;color:#0F766E;">✓</td>
          <td class="desc">lambda, dict, función</td>
          <td><span class="rb rb-green">Actual</span></td>
        </tr>
        <tr>
          <td><code class="ic">.applymap()</code></td>
          <td style="text-align:center;color:#ef4444;">✗</td>
          <td style="text-align:center;color:#0F766E;">✓</td>
          <td class="desc">lambda, función</td>
          <td><span class="rb rb-amber">Deprecado</span></td>
        </tr>
        <tr>
          <td><code class="ic">.apply()</code></td>
          <td style="text-align:center;color:#0F766E;">✓</td>
          <td style="text-align:center;color:#0F766E;">✓</td>
          <td class="desc">lambda, función</td>
          <td><span class="rb rb-green">Actual</span></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="nb-note">
    <i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="nb-note-text">
      Para transformaciones elemento a elemento, <code class="ic">.map()</code> es
      <strong>hasta 10 veces más rápido</strong> que <code class="ic">.apply()</code>.
      Reserva <code class="ic">.apply()</code> para operaciones sobre filas o columnas completas
      donde necesites más flexibilidad.
    </span>
  </div>

  <div class="warn-box">
    <i class="ti ti-alert-triangle" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="warn-text"><code class="ic">.applymap()</code> sigue funcionando pero genera un <strong>FutureWarning</strong>. Usa siempre <code class="ic">.map()</code> para evitarlo.</span>
  </div>
</div>

In [21]:
# Con .applymap() podemos aplicar funciones a varias columnas a la vez
# Esto es un método propio de los DataFrames

df[["Name", "Sex"]].applymap(lambda x : x.lower())

/tmp/ipykernel_7656/1973307892.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[["Name", "Sex"]].applymap(lambda x : x.lower())

                                                  Name     Sex
0                              braund, mr. owen harris    male
1    cumings, mrs. john bradley (florence briggs th...  female
2                               heikkinen, miss. laina  female
3         futrelle, mrs. jacques heath (lily may peel)  female
4                             allen, mr. william henry    male
..                                                 ...     ...
886                              montvila, rev. juozas    male
887                       graham, miss. margaret edith  female
888           johnston, miss. catherine helen "carrie"  female
889                              behr, mr. karl howell    male
890                                dooley, mr. patrick    male

[891 rows x 2 columns]

In [22]:
# map también funciona en versiones recientes de pandas
df[["Name", "Sex"]].map(lambda x: x.upper())

                                                  Name     Sex
0                              BRAUND, MR. OWEN HARRIS    MALE
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...  FEMALE
2                               HEIKKINEN, MISS. LAINA  FEMALE
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)  FEMALE
4                             ALLEN, MR. WILLIAM HENRY    MALE
..                                                 ...     ...
886                              MONTVILA, REV. JUOZAS    MALE
887                       GRAHAM, MISS. MARGARET EDITH  FEMALE
888           JOHNSTON, MISS. CATHERINE HELEN "CARRIE"  FEMALE
889                              BEHR, MR. KARL HOWELL    MALE
890                                DOOLEY, MR. PATRICK    MALE

[891 rows x 2 columns]

In [23]:
# .apply() Se puede utilizar para Series y DataFrames

df["Age"].apply(lambda x : np.sqrt(x))

0      4.690416
1      6.164414
2      5.099020
3      5.916080
4      5.916080
         ...
886    5.196152
887    4.358899
888         NaN
889    5.099020
890    5.656854
Name: Age, Length: 891, dtype: float64

In [24]:
# apply sobre varias columnas
df[["PassengerId", "Age"]].apply(lambda x: np.sqrt(x))

     PassengerId       Age
0       1.000000  4.690416
1       1.414214  6.164414
2       1.732051  5.099020
3       2.000000  5.916080
4       2.236068  5.916080
..           ...       ...
886    29.782545  5.196152
887    29.799329  4.358899
888    29.816103       NaN
889    29.832868  5.099020
890    29.849623  5.656854

[891 rows x 2 columns]

In [26]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:30%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Valores de una Serie y gestión de NaN</h3>
  <hr class="nb-divider">
  <div class="nb-body-box">
    En pandas, los valores nulos se representan como <code class="ic">NaN</code> (<em>Not a Number</em>).
    La mayoría de operaciones los omiten automáticamente, pero es importante saber detectarlos,
    contarlos y decidir si eliminarlos o rellenarlos.
  </div>
  <div class="table-wrap" style="overflow:visible;">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Método / Atributo</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Descripción</th>
      </tr></thead>
      <tbody>
        <tr>
          <td><span class="tip"><code class="ic">.values</code><span class="tt">Devuelve un array de NumPy con los elementos de la columna, sin el índice.</span></span></td>
          <td class="desc">Array NumPy con los elementos de la Serie</td>
        </tr>
        <tr>
          <td><span class="tip"><code class="ic">.value_counts(dropna=False)</code><span class="tt">Por defecto dropna=True omite los NaN. Con dropna=False los incluye en el conteo.</span></span></td>
          <td class="desc">Conteo de valores incluyendo <strong>NaN</strong></td>
        </tr>
        <tr>
          <td><span class="tip"><code class="ic">.isnull()</code><span class="tt">Devuelve una Serie booleana: True donde hay NaN, False donde hay valor. Usar como filtro sobre el DataFrame.</span></span></td>
          <td class="desc">Filtra las filas con <strong>NaN</strong></td>
        </tr>
        <tr>
          <td><span class="tip"><code class="ic">.dropna()</code><span class="tt">Elimina todas las filas que tengan al menos un NaN en cualquier columna. No es in-place por defecto.</span></span></td>
          <td class="desc">Elimina filas con NaN — <strong>no in-place</strong></td>
        </tr>
        <tr>
          <td><span class="tip"><code class="ic">.fillna(valor)</code><span class="tt">Sustituye todos los NaN por el valor indicado. Puede ser 0, la media, la mediana, etc.</span></span></td>
          <td class="desc">Rellena NaN con un valor específico</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="warn-box" style="margin-top:.8rem;">
    <i class="ti ti-alert-triangle" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="warn-text"><code class="ic">df.dropna(inplace=True)</code> elimina permanentemente las filas con NaN. Asegúrate de que es lo que quieres antes de ejecutarlo.</span>
  </div>
  <div class="hint" style="margin-top:.5rem;"><i class="ti ti-info-circle" style="font-size:13px;"></i> Una buena práctica es rellenar los NaN con la <strong>media o mediana</strong> de la columna: <code class="ic">df["Age"].fillna(df["Age"].mean())</code></div>
</div>

In [27]:
# Array con los valores de la columna
df["Sex"].values

array(['male', 'female', 'female', 'female', 'male', 'male', 'male',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'female', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'female', 'male', 'male', 'male',
       'female', 'female', 'female', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'female',
       'male', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'male', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'female', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'female', 'female', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'female', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'female', 'female', 'female', 'male', 'female',
       'male', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'female', 'female',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'female', 'male', 'female', 'female',
       'female', 'female', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'male', 'male',
       'male', 'female', 'female', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'female', 'male', 'male', 'female', 'male', 'male',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'male', 'male', 'female', 'female', 'female', 'male', 'male',
       'male', 'female', 'female', 'male', 'female', 'male', 'male',
       'male', 'female', 'male', 'female', 'male', 'male', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'male', 'male', 'female', 'male', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'female', 'male', 'male',
       'female', 'female', 'female', 'male', 'female', 'male', 'male',
       'male', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'male', 'female', 'female', 'male', 'male', 'female',
       'female', 'female', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'male', 'female', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'male', 'female', 'male', 'female', 'male', 'male', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'female', 'female', 'male', 'female', 'male',
       'female', 'female', 'female', 'female', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'female', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'female', 'female', 'male', 'female', 'female', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'female', 'female', 'female', 'male', 'female',
       'male', 'male', 'female', 'male', 'female', 'female', 'male',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'female', 'female',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'female', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'female', 'female', 'male', 'male', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'female', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'female', 'female', 'female', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'male', 'female', 'female', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'male', 'female', 'male',
       'male', 'male', 'female', 'female', 'male', 'female', 'female',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male'], dtype=object)

In [28]:
# value_counts omite NaN por defecto
df["Age"].value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [29]:
# Incluir NaN en el conteo
df["Age"].value_counts(dropna=False)

Age
NaN      177
24.00     30
22.00     27
18.00     26
28.00     25
        ...
24.50      1
0.67       1
0.42       1
34.50      1
74.00      1
Name: count, Length: 89, dtype: int64

In [30]:
# Filtrar filas con NaN
df[df["Age"].isnull()]

,PassengerId,Name,Sex,Age,AgeSQRT,Surname
5,6,"Moran, Mr. James",male,NaN,NaN,Moran
17,18,"Williams, Mr. Charles Eugene",male,NaN,NaN,Williams
19,20,"Masselmani, Mrs. Fatima",female,NaN,NaN,Masselmani
26,27,"Emir, Mr. Farred Chehab",male,NaN,NaN,Emir
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,NaN,O'Dwyer
...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,NaN,Razi
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,NaN,Sage
868,869,"van Melkebeke, Mr. Philemon",male,NaN,NaN,van Melkebeke
878,879,"Laleff, Mr. Kristo",male,NaN,NaN,Laleff
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,NaN,Johnston

In [31]:
# Eliminar filas con NaN (no in-place)
df.dropna()

,PassengerId,Name,Sex,Age,AgeSQRT,Surname
0,1,"Braund, Mr. Owen Harris",male,22.0,4.690416,Braund
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,6.164414,Cumings
2,3,"Heikkinen, Miss. Laina",female,26.0,5.099020,Heikkinen
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,5.916080,Futrelle
4,5,"Allen, Mr. William Henry",male,35.0,5.916080,Allen
...,...,...,...,...,...,...
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.0,6.244998,Rice
886,887,"Montvila, Rev. Juozas",male,27.0,5.196152,Montvila
887,888,"Graham, Miss. Margaret Edith",female,19.0,4.358899,Graham
889,890,"Behr, Mr. Karl Howell",male,26.0,5.099020,Behr
890,891,"Dooley, Mr. Patrick",male,32.0,5.656854,Dooley

In [33]:
# Si quisieramos que fuese in-place podemos escribir:

#df.dropna(inplace = True)

# NO EJECUTAR

In [34]:
# Rellenar NaN con 0
df["Age"] = df["Age"].fillna(0)
df.head()

,PassengerId,Name,Sex,Age,AgeSQRT,Surname
0,1,"Braund, Mr. Owen Harris",male,22.0,4.690416,Braund
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,6.164414,Cumings
2,3,"Heikkinen, Miss. Laina",female,26.0,5.099020,Heikkinen
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,5.916080,Futrelle
4,5,"Allen, Mr. William Henry",male,35.0,5.916080,Allen

In [35]:
df = pd.read_excel("Data/Canada.xlsx")
df.head(3)

,Tipo,Pais,Area,Continente,Region,Nombre de region,Tipo de region,1980,1981,1982,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Afghanistan,935,Asia,5501,Southern Asia,Developing regions,16,39,39,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Albania,908,Europe,925,Southern Europe,Developed regions,1,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Algeria,903,Africa,912,Northern Africa,Developing regions,80,67,71,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331

In [36]:
df["Continente"].value_counts()

Continente
Africa                             54
Asia                               49
Europe                             43
Latin America and the Caribbean    33
Oceania                            14
Northern America                    2
Name: count, dtype: int64

In [37]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:30%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">DataFrame.groupby()</h3>
  <hr class="nb-divider">
  <div class="nb-body-box">
    <code class="ic">.groupby()</code> agrupa las filas que tienen el mismo valor en una o varias columnas.
    Por sí solo devuelve un objeto de agrupación — siempre debe combinarse con una
    <strong>función agregada</strong> para producir un resultado útil.
  </div>
 <div class="table-wrap" style="overflow:visible;">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Función agregada</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Descripción</th>
      </tr></thead>
      <tbody>
        <tr><td><span class="tip"><code class="ic">.first()</code><span class="tt">Devuelve el primer elemento de cada grupo. Útil para ver un representante de cada categoría.</span></span></td><td class="desc">Primer elemento de cada grupo</td></tr>
        <tr><td><span class="tip"><code class="ic">.last()</code><span class="tt">Devuelve el último elemento de cada grupo.</span></span></td><td class="desc">Último elemento de cada grupo</td></tr>
        <tr><td><span class="tip"><code class="ic">.size()</code><span class="tt">Cuenta el número total de filas por grupo, incluyendo NaN. Distinto de .count().</span></span></td><td class="desc">Número de filas por grupo (incluye NaN)</td></tr>
        <tr><td><span class="tip"><code class="ic">.count()</code><span class="tt">Cuenta solo los valores no nulos por columna en cada grupo.</span></span></td><td class="desc">Número de valores <strong>no NaN</strong> por grupo</td></tr>
        <tr><td><span class="tip"><code class="ic">.sum()</code><span class="tt">Suma todos los valores numéricos de cada grupo.</span></span></td><td class="desc">Suma de cada grupo</td></tr>
        <tr><td><span class="tip"><code class="ic">.max() / .min()</code><span class="tt">Valor máximo o mínimo de cada grupo.</span></span></td><td class="desc">Máximo / mínimo de cada grupo</td></tr>
        <tr><td><span class="tip"><code class="ic">.aggregate([f1, f2])</code><span class="tt">Aplica varias funciones a todas las columnas seleccionadas. El resultado tiene multi-índice en columnas.</span></span></td><td class="desc">Varias funciones a la vez sobre todas las columnas</td></tr>
        <tr><td><span class="tip"><code class="ic">.agg(&#123;col: [f1, f2]&#125;)</code><span class="tt">Permite elegir qué función aplicar a qué columna usando un diccionario.</span></span></td><td class="desc">Funciones distintas por columna</td></tr>
      </tbody>
    </table>
  </div>
  <div class="hint"><i class="ti ti-info-circle" style="font-size:13px;"></i> Pasa el cursor sobre cada función para ver detalles adicionales.</div>
</div>

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:30%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">groupby() — ejemplos</h3>
  <hr class="nb-divider">

</div>

In [38]:
# .groupby() se usa para agrupar filas que tienen los mismos valores.
# Obligatoriamente se usa junto con funciones agregadas para producir informes resumidos.

df.groupby("Continente")

# Me devuelve el objeto de la agrupación

In [39]:
# .first() Me devuelve un elemento de cada agrupación

df.groupby("Continente").first()

,Tipo,Pais,Area,Region,Nombre de region,Tipo de region,1980,1981,1982,1983,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Continente,,,,,,,,,,,,,,,,,,,,,
Africa,Immigrants,Algeria,903,912,Northern Africa,Developing regions,80,67,71,69,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
Asia,Immigrants,Afghanistan,935,5501,Southern Asia,Developing regions,16,39,39,47,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
Europe,Immigrants,Albania,908,925,Southern Europe,Developed regions,1,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
Latin America and the Caribbean,Immigrants,Antigua and Barbuda,904,915,Caribbean,Developing regions,0,0,0,0,...,14,24,32,15,32,38,27,37,51,25
Northern America,Immigrants,Canada,905,905,Northern America,Developed regions,0,0,0,0,...,0,0,0,0,0,0,0,1,1,2
Oceania,Immigrants,American Samoa,909,957,Polynesia,Developing regions,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0

In [41]:
# .size() Devuelve el tamaño de cada grupo de la agrupación

df.groupby(["Continente"]).size()

Continente
Africa                             54
Asia                               49
Europe                             43
Latin America and the Caribbean    33
Northern America                    2
Oceania                            14
dtype: int64

In [42]:
# Podemos agrupar por más de una columna

df.groupby(["Continente", "Tipo de region"]).first()

                                                          Tipo  \
Continente                      Tipo de region
Africa                          Developing regions  Immigrants
Asia                            Developed regions   Immigrants
                                Developing regions  Immigrants
Europe                          Developed regions   Immigrants
Latin America and the Caribbean Developing regions  Immigrants
Northern America                Developed regions   Immigrants
Oceania                         Developed regions   Immigrants
                                Developing regions  Immigrants

                                                                   Pais  Area  \
Continente                      Tipo de region
Africa                          Developing regions              Algeria   903
Asia                            Developed regions                 Japan   935
                                Developing regions          Afghanistan   935
Europe                          Developed regions               Albania   908
Latin America and the Caribbean Developing regions  Antigua and Barbuda   904
Northern America                Developed regions                Canada   905
Oceania                         Developed regions             Australia   909
                                Developing regions       American Samoa   909

                                                    Region  \
Continente                      Tipo de region
Africa                          Developing regions     912
Asia                            Developed regions      906
                                Developing regions    5501
Europe                          Developed regions      925
Latin America and the Caribbean Developing regions     915
Northern America                Developed regions      905
Oceania                         Developed regions      927
                                Developing regions     957

                                                             Nombre de region  \
Continente                      Tipo de region
Africa                          Developing regions            Northern Africa
Asia                            Developed regions                Eastern Asia
                                Developing regions              Southern Asia
Europe                          Developed regions             Southern Europe
Latin America and the Caribbean Developing regions                  Caribbean
Northern America                Developed regions            Northern America
Oceania                         Developed regions   Australia and New Zealand
                                Developing regions                  Polynesia

                                                    1980  1981  1982  1983  \
Continente                      Tipo de region
Africa                          Developing regions    80    67    71    69
Asia                            Developed regions    701   756   598   309
                                Developing regions    16    39    39    47
Europe                          Developed regions      1     0     0     0
Latin America and the Caribbean Developing regions     0     0     0     0
Northern America                Developed regions      0     0     0     0
Oceania                         Developed regions    702   639   484   317
                                Developing regions     0     1     0     0

                                                    1984  ...  2004  2005  \
Continente                      Tipo de region            ...
Africa                          Developing regions    63  ...  3616  3626
Asia                            Developed regions    246  ...   973  1067
                                Developing regions    71  ...  2978  3436
Europe                          Developed regions      0  ...  1450  1223
Latin America and the Caribbean Developing regions    42  ...    14    24
Northern America                Developed regions      0  ...     0     0
Oceania                         Developed regions    317  ...   930   909
                                Developing regions     0  ...     0     0

                                                    2006  2007  2008  2009  \
Continente                      Tipo de region
Africa                          Developing regions  4807  3623  4005  5393
Asia                            Developed regions   1212  1250  1284  1194
                                Developing regions  3009  2652  2111  1746
Europe                          Developed regions    856   702   560   716
Latin America and the Caribbean Developing regions    32    15    32    38
Northern America                Developed regions      0     0     0     0
Oceania                         Developed regions    875  1033  1018  1018
                                Developing regions     1     0     0     0

                                                    2010  2011  2012  2013
Continente                      Tipo de region
Africa                          Developing regions  4752  4325  3774  4331
Asia                            Developed regions   1168  1265  1214   982
                                Developing regions  1758  2203  2635  2004
Europe                          Developed regions    561   539   620   603
Latin America and the Caribbean Developing regions    27    37    51    25
Northern America                Developed regions      0     1     1     2
Oceania                         Developed regions    933   851   982  1121
                                Developing regions     0     0     0     0

[8 rows x 39 columns]

In [43]:
df.groupby(["Tipo de region", "Continente"]).first()

                                                          Tipo  \
Tipo de region     Continente
Developed regions  Asia                             Immigrants
                   Europe                           Immigrants
                   Northern America                 Immigrants
                   Oceania                          Immigrants
Developing regions Africa                           Immigrants
                   Asia                             Immigrants
                   Latin America and the Caribbean  Immigrants
                   Oceania                          Immigrants

                                                                   Pais  Area  \
Tipo de region     Continente
Developed regions  Asia                                           Japan   935
                   Europe                                       Albania   908
                   Northern America                              Canada   905
                   Oceania                                    Australia   909
Developing regions Africa                                       Algeria   903
                   Asia                                     Afghanistan   935
                   Latin America and the Caribbean  Antigua and Barbuda   904
                   Oceania                               American Samoa   909

                                                    Region  \
Tipo de region     Continente
Developed regions  Asia                                906
                   Europe                              925
                   Northern America                    905
                   Oceania                             927
Developing regions Africa                              912
                   Asia                               5501
                   Latin America and the Caribbean     915
                   Oceania                             957

                                                             Nombre de region  \
Tipo de region     Continente
Developed regions  Asia                                          Eastern Asia
                   Europe                                     Southern Europe
                   Northern America                          Northern America
                   Oceania                          Australia and New Zealand
Developing regions Africa                                     Northern Africa
                   Asia                                         Southern Asia
                   Latin America and the Caribbean                  Caribbean
                   Oceania                                          Polynesia

                                                    1980  1981  1982  1983  \
Tipo de region     Continente
Developed regions  Asia                              701   756   598   309
                   Europe                              1     0     0     0
                   Northern America                    0     0     0     0
                   Oceania                           702   639   484   317
Developing regions Africa                             80    67    71    69
                   Asia                               16    39    39    47
                   Latin America and the Caribbean     0     0     0     0
                   Oceania                             0     1     0     0

                                                    1984  ...  2004  2005  \
Tipo de region     Continente                             ...
Developed regions  Asia                              246  ...   973  1067
                   Europe                              0  ...  1450  1223
                   Northern America                    0  ...     0     0
                   Oceania                           317  ...   930   909
Developing regions Africa                             63  ...  3616  3626
                   Asia                               71  ...  2978  3436
                   Latin America and the Caribbean    42  ...    14    24
                   Oceania                             0  ...     0     0

                                                    2006  2007  2008  2009  \
Tipo de region     Continente
Developed regions  Asia                             1212  1250  1284  1194
                   Europe                            856   702   560   716
                   Northern America                    0     0     0     0
                   Oceania                           875  1033  1018  1018
Developing regions Africa                           4807  3623  4005  5393
                   Asia                             3009  2652  2111  1746
                   Latin America and the Caribbean    32    15    32    38
                   Oceania                             1     0     0     0

                                                    2010  2011  2012  2013
Tipo de region     Continente
Developed regions  Asia                             1168  1265  1214   982
                   Europe                            561   539   620   603
                   Northern America                    0     1     1     2
                   Oceania                           933   851   982  1121
Developing regions Africa                           4752  4325  3774  4331
                   Asia                             1758  2203  2635  2004
                   Latin America and the Caribbean    27    37    51    25
                   Oceania                             0     0     0     0

[8 rows x 39 columns]

In [44]:
# .index nos retorna la forma del indice del DataFrame

df.groupby(["Tipo de region", "Continente"]).first().index

MultiIndex([( 'Developed regions',                            'Asia'),
            ( 'Developed regions',                          'Europe'),
            ( 'Developed regions',                'Northern America'),
            ( 'Developed regions',                         'Oceania'),
            ('Developing regions',                          'Africa'),
            ('Developing regions',                            'Asia'),
            ('Developing regions', 'Latin America and the Caribbean'),
            ('Developing regions',                         'Oceania')],
           names=['Tipo de region', 'Continente'])

In [45]:
# .last() Devuelve el último elemento de la agrupación
df.groupby(["Continente"]).last()

,Tipo,Pais,Area,Region,Nombre de region,Tipo de region,1980,1981,1982,1983,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Continente,,,,,,,,,,,,,,,,,,,,,
Africa,Immigrants,Zimbabwe,903,910,Eastern Africa,Developing regions,72,114,102,44,...,1450,615,454,663,611,508,494,434,437,407
Asia,Immigrants,Yemen,935,922,Western Asia,Developing regions,1,2,1,6,...,124,161,140,122,133,128,211,160,174,217
Europe,Immigrants,United Kingdom of Great Britain and Northern I...,908,924,Northern Europe,Developed regions,22045,24796,20620,10015,...,7533,7258,7140,8216,8979,8876,8724,6204,6195,5827
Latin America and the Caribbean,Immigrants,Venezuela (Bolivarian Republic of),904,931,South America,Developing regions,103,117,174,124,...,1224,1211,1192,1335,1239,1353,998,1452,1373,1022
Northern America,Immigrants,United States of America,905,905,Northern America,Developed regions,9378,10030,9074,7100,...,6990,8394,9613,9463,10190,8995,8142,7676,7891,8501
Oceania,Immigrants,Vanuatu,909,928,Melanesia,Developing regions,0,0,0,0,...,1,1,1,0,0,1,0,0,0,0

In [46]:
#  .count() Cuenta el número de elementos que no son NaN's

df.groupby(["Continente"]).count()

,Tipo,Pais,Area,Region,Nombre de region,Tipo de region,1980,1981,1982,1983,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Continente,,,,,,,,,,,,,,,,,,,,,
Africa,54,54,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,54,54,54
Asia,49,49,49,49,49,49,49,49,49,49,...,49,49,49,49,49,49,49,49,49,49
Europe,43,43,43,43,43,43,43,43,43,43,...,43,43,43,43,43,43,43,43,43,43
Latin America and the Caribbean,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
Northern America,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Oceania,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14

In [47]:
# Agrupamos por continente y luego sumamos la migración de cada continente en el año 1980

df.groupby("Continente")[1980].sum()

Continente
Africa                              3951
Asia                               31025
Europe                             39760
Latin America and the Caribbean    13081
Northern America                    9378
Oceania                             1942
Name: 1980, dtype: int64

In [48]:
# Equivalente con bucle for
dict_cont = {}
for cont, valor in df[["Continente", 1980]].values:
    if cont not in dict_cont.keys():
        dict_cont[cont] = valor
    else:
        dict_cont[cont] = dict_cont[cont] + valor
dict_cont

{'Asia': 31025,
 'Europe': 39760,
 'Africa': 3951,
 'Oceania': 1942,
 'Latin America and the Caribbean': 13081,
 'Northern America': 9378}

In [49]:
df.groupby("Continente")[[2008, 2009, 2010]].sum()

                                   2008    2009    2010
Continente
Africa                            29890   34534   40892
Asia                             139894  141434  163845
Europe                            34692   35078   33425
Latin America and the Caribbean   26547   26867   28818
Northern America                  10190    8995    8142
Oceania                            1834    1860    1834

In [50]:
# Para encontrar los valores máximos de cada continente en el año 1980

df.groupby("Continente")[1980].max()

Continente
Africa                              1026
Asia                                8880
Europe                             22045
Latin America and the Caribbean     3198
Northern America                    9378
Oceania                              702
Name: 1980, dtype: int64

In [52]:
# .aggregate() toma una lista de funciones agregadas y las aplica a todas las columnas

df.groupby("Continente")[[2010, 2011, 2012]].aggregate(["min", "max", "sum"])

                                2010                2011                2012  \
                                 min    max     sum  min    max     sum  min
Continente
Africa                             0   6242   40892    0   4663   35441    0
Asia                               4  38617  163845    3  36765  146894    1
Europe                             0   8724   33425    0   6204   26778    0
Latin America and the Caribbean   13   5218   28818   11   6503   27856   16
Northern America                   0   8142    8142    1   7676    7677    1
Oceania                            0    933    1834    0    851    1548    0


                                   max     sum
Continente
Africa                            5555   38083
Asia                             34315  152218
Europe                            6280   29177
Latin America and the Caribbean   5868   27173
Northern America                  7891    7892
Oceania                            982    1679

In [53]:
df.groupby("Continente")[list(range(1980, 2014))].aggregate(["min", "max", "sum"])

                                1980               1981               1982  \
                                 min    max    sum  min    max    sum  min
Continente
Africa                             0   1026   3951    0   1118   4363    0
Asia                               0   8880  31025    0   8670  34314    0
Europe                             0  22045  39760    0  24796  44802    0
Latin America and the Caribbean    0   3198  13081    0   3692  15215    0
Northern America                   0   9378   9378    0  10030  10030    0
Oceania                            0    702   1942    0    705   1839    0

                                              1983  ...    2010 2011         \
                                   max    sum  min  ...     sum  min    max
Continente                                          ...
Africa                             781   3819    0  ...   40892    0   4663
Asia                              8147  30214    0  ...  163845    3  36765
Europe                           20620  42720    0  ...   33425    0   6204
Latin America and the Caribbean   3575  16769    0  ...   28818   11   6503
Northern America                  9074   9074    0  ...    8142    1   7676
Oceania                            814   1675    0  ...    1834    0    851

                                        2012                2013         \
                                    sum  min    max     sum  min    max
Continente
Africa                            35441    0   5555   38083    0   4331
Asia                             146894    1  34315  152218    1  34129
Europe                            26778    0   6280   29177    0   5827
Latin America and the Caribbean   27856   16   5868   27173    4   4152
Northern America                   7677    1   7891    7892    2   8501
Oceania                            1548    0    982    1679    0   1121


                                    sum
Continente
Africa                            38543
Asia                             155075
Europe                            28691
Latin America and the Caribbean   24950
Northern America                   8503
Oceania                            1775

[6 rows x 102 columns]

In [54]:
# .agg() toma como parametro un diccionario
# Las llaves son los nombres de las columnas
# Los valores son listas de funciones agregadas
# Aquí podemos elegir a que columnas aplicar que funcion

df.groupby("Continente").agg({2010 : ["min", "max", "sum", "std"],
                              2011 : ["min", "max", "mean"],
                              2012 : ["sum", "median"]})

                                2010                             2011         \
                                 min    max     sum          std  min    max
Continente
Africa                             0   6242   40892  1393.241018    0   4663
Asia                               4  38617  163845  8280.593508    3  36765
Europe                             0   8724   33425  1595.029940    0   6204
Latin America and the Caribbean   13   5218   28818  1356.514681   11   6503
Northern America                   0   8142    8142  5757.263412    1   7676
Oceania                            0    933    1834   281.315317    0    851

                                                2012
                                        mean     sum  median
Continente
Africa                            656.314815   38083   206.5
Asia                             2997.836735  152218   296.0
Europe                            622.744186   29177   173.0
Latin America and the Caribbean   844.121212   27173   291.0
Northern America                 3838.500000    7892  3946.0
Oceania                           110.571429    1679     1.0

In [55]:
df5 = df.groupby("Continente").agg({2010 : ["min","max","sum"],
                                    2011 : ["min","max"],
                                    2012 : ["sum"]})

df5.reset_index()

                        Continente 2010                2011           2012
                                    min    max     sum  min    max     sum
0                           Africa    0   6242   40892    0   4663   38083
1                             Asia    4  38617  163845    3  36765  152218
2                           Europe    0   8724   33425    0   6204   29177
3  Latin America and the Caribbean   13   5218   28818   11   6503   27173
4                 Northern America    0   8142    8142    1   7676    7892
5                          Oceania    0    933    1834    0    851    1679

In [56]:
# Para tener un resultados como el anterior, podemos pasarle un parametro extra a .groupby()

df.groupby("Continente", as_index = False).agg({2010 : ["min","max","sum"],
                                                2011 : ["min","max"],
                                                2012 : ["sum"]})

                        Continente 2010                2011           2012
                                    min    max     sum  min    max     sum
0                           Africa    0   6242   40892    0   4663   38083
1                             Asia    4  38617  163845    3  36765  152218
2                           Europe    0   8724   33425    0   6204   29177
3  Latin America and the Caribbean   13   5218   28818   11   6503   27173
4                 Northern America    0   8142    8142    1   7676    7892
5                          Oceania    0    933    1834    0    851    1679

In [58]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin:1rem 0;border:none;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Eliminar multi-índice en columnas</h3>
  <hr class="nb-divider">

  <div class="nb-body-box">
    Cuando se usa <code class="ic">.agg()</code> con varias funciones, pandas genera un
    <strong>multi-índice</strong> en las columnas (ej: <code class="ic">(2010, "min")</code>,
    <code class="ic">(2010, "max")</code>…). Hay dos formas de resolverlo:
    aplanar el resultado con una list comprehension, o evitarlo desde el principio
    usando <strong>Named Aggregation</strong>.
  </div>

  <p style="font-size:12px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;">
    Opción A — Aplanar con list comprehension (clásica)
  </p>

  <div class="code-block">
    <div class="code-header">
      <div class="dots"><div class="dot dot-r"></div><div class="dot dot-y"></div><div class="dot dot-g"></div></div>
      <span class="code-lang">Python</span>
    </div>
    <pre class="cc"><span class="al">df5</span> <span class="op">=</span> df.groupby(<span class="st">"Continente"</span>).agg({
    <span class="num">2010</span>: [<span class="st">"min"</span>, <span class="st">"max"</span>, <span class="st">"sum"</span>],
    <span class="num">2011</span>: [<span class="st">"min"</span>, <span class="st">"max"</span>],
    <span class="num">2012</span>: [<span class="st">"sum"</span>]
})

<span class="cm"># El resultado tiene multi-índice: (2010, "min"), (2010, "max")…</span>
<span class="fn">print</span>(<span class="al">df5</span>.columns)

<span class="cm"># Aplanar con list comprehension</span>
<span class="al">df5</span>.columns <span class="op">=</span> [<span class="fn">f</span><span class="st">"{x[0]}_{x[1]}"</span> <span class="kw">for</span> x <span class="kw">in</span> <span class="al">df5</span>.columns.values]
<span class="al">df5</span>.reset_index()</pre>
  </div>

  <hr class="nb-divider-sm">

  <p style="font-size:12px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;">
    Opción B — Named Aggregation (moderna, sin multi-índice)
  </p>

  <div class="code-block">
    <div class="code-header">
      <div class="dots"><div class="dot dot-r"></div><div class="dot dot-y"></div><div class="dot dot-g"></div></div>
      <span class="code-lang">Python</span>
    </div>
    <pre class="cc"><span class="cm"># Cada argumento define directamente el nombre de la columna resultante</span>
df.groupby(<span class="st">"Continente"</span>).agg(
    min_2010 <span class="op">=</span> (<span class="num">2010</span>, <span class="st">"min"</span>),
    max_2010 <span class="op">=</span> (<span class="num">2010</span>, <span class="st">"max"</span>),
    sum_2010 <span class="op">=</span> (<span class="num">2010</span>, <span class="st">"sum"</span>),
    min_2011 <span class="op">=</span> (<span class="num">2011</span>, <span class="st">"min"</span>),
    max_2011 <span class="op">=</span> (<span class="num">2011</span>, <span class="st">"max"</span>),
    sum_2012 <span class="op">=</span> (<span class="num">2012</span>, <span class="st">"sum"</span>)
)</pre>
  </div>

  <div class="nb-note">
    <i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="nb-note-text">
      La <strong>Opción B</strong> es la forma recomendada en pandas moderno — evita el multi-índice
      desde el principio y produce columnas con nombres legibles directamente, sin necesitar
      list comprehension posterior. La sintaxis es
      <code class="ic">nombre_columna = (columna_original, "función")</code>.
    </span>
  </div>

  <div class="warn-box">
    <i class="ti ti-alert-triangle" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="warn-text">
      Usa siempre las funciones como <strong>strings</strong>:
      <code class="ic">"min"</code>, <code class="ic">"max"</code>, <code class="ic">"sum"</code>…
      Pasar las funciones de Python directamente (<code class="ic">min</code>, <code class="ic">max</code>)
      genera un <strong>FutureWarning</strong> en pandas 3.x.
    </span>
  </div>

</div>